/**
 * Curated problem list constants.
 * Each array contains LeetCode slugs (problem IDs) for that list.
 * Used by the Problems page List dropdown to filter client-side.
 */

export const BLIND_75: ReadonlySet<string> = new Set([
  "two-sum",
  "best-time-to-buy-and-sell-stock",
  "contains-duplicate",
  "product-of-array-except-self",
  "maximum-subarray",
  "maximum-product-subarray",
  "find-minimum-in-rotated-sorted-array",
  "search-in-rotated-sorted-array",
  "3sum",
  "container-with-most-water",
  "sum-of-two-integers",
  "number-of-1-bits",
  "counting-bits",
  "missing-number",
  "reverse-bits",
  "climbing-stairs",
  "coin-change",
  "longest-increasing-subsequence",
  "longest-common-subsequence",
  "word-break",
  "combination-sum",
  "house-robber",
  "house-robber-ii",
  "decode-ways",
  "unique-paths",
  "jump-game",
  "longest-substring-without-repeating-characters",
  "longest-repeating-character-replacement",
  "minimum-window-substring",
  "valid-anagram",
  "group-anagrams",
  "valid-parentheses",
  "valid-palindrome",
  "longest-palindromic-substring",
  "palindromic-substrings",
  "invert-binary-tree",
  "maximum-depth-of-binary-tree",
  "same-tree",
  "subtree-of-another-tree",
  "lowest-common-ancestor-of-a-binary-tree",
  "binary-tree-level-order-traversal",
  "validate-binary-search-tree",
  "kth-smallest-element-in-a-bst",
  "construct-binary-tree-from-preorder-and-inorder-traversal",
  "binary-tree-maximum-path-sum",
  "top-k-frequent-elements",
  "merge-k-sorted-lists",
  "number-of-islands",
  "course-schedule",
  "pacific-atlantic-water-flow",
  "longest-consecutive-sequence",
  "merge-intervals",
  "insert-interval",
  "non-overlapping-intervals",
  "set-matrix-zeroes",
  "spiral-matrix",
  "rotate-image",
  "word-search",
  "reverse-linked-list",
  "merge-two-sorted-lists",
  "reorder-list",
  "remove-nth-node-from-end-of-list",
  "linked-list-cycle",
]);

export const NEETCODE_150: ReadonlySet<string> = new Set([
  // Arrays & Hashing
  "contains-duplicate",
  "valid-anagram",
  "two-sum",
  "group-anagrams",
  "top-k-frequent-elements",
  "product-of-array-except-self",
  "valid-sudoku",
  "longest-consecutive-sequence",
  // Two Pointers
  "valid-palindrome",
  "two-sum-ii-input-array-is-sorted",
  "3sum",
  "container-with-most-water",
  "trapping-rain-water",
  // Sliding Window
  "best-time-to-buy-and-sell-stock",
  "longest-substring-without-repeating-characters",
  "longest-repeating-character-replacement",
  "permutation-in-string",
  "minimum-window-substring",
  "sliding-window-maximum",
  // Stack
  "valid-parentheses",
  "evaluate-reverse-polish-notation",
  "generate-parentheses",
  "daily-temperatures",
  "car-fleet",
  "largest-rectangle-in-histogram",
  // Binary Search
  "binary-search",
  "search-a-2d-matrix",
  "koko-eating-bananas",
  "find-minimum-in-rotated-sorted-array",
  "search-in-rotated-sorted-array",
  "median-of-two-sorted-arrays",
  // Linked List
  "reverse-linked-list",
  "merge-two-sorted-lists",
  "reorder-list",
  "remove-nth-node-from-end-of-list",
  "linked-list-cycle",
  "merge-k-sorted-lists",
  "reverse-nodes-in-k-group",
  // Trees
  "invert-binary-tree",
  "maximum-depth-of-binary-tree",
  "diameter-of-binary-tree",
  "balanced-binary-tree",
  "same-tree",
  "subtree-of-another-tree",
  "lowest-common-ancestor-of-a-binary-tree",
  "binary-tree-level-order-traversal",
  "binary-tree-right-side-view",
  "count-good-nodes-in-binary-tree",
  "validate-binary-search-tree",
  "kth-smallest-element-in-a-bst",
  "construct-binary-tree-from-preorder-and-inorder-traversal",
  "binary-tree-maximum-path-sum",
  // Heap / Priority Queue
  "kth-largest-element-in-an-array",
  "last-stone-weight",
  "k-closest-points-to-origin",
  "task-scheduler",
  // Backtracking
  "subsets",
  "combination-sum",
  "combination-sum-ii",
  "permutations",
  "subsets-ii",
  "word-search",
  "palindrome-partitioning",
  "letter-combinations-of-a-phone-number",
  "n-queens",
  // Graphs
  "number-of-islands",
  "max-area-of-island",
  "pacific-atlantic-water-flow",
  "surrounded-regions",
  "rotting-oranges",
  "course-schedule",
  "course-schedule-ii",
  "redundant-connection",
  "word-ladder",
  // Dynamic Programming
  "climbing-stairs",
  "min-cost-climbing-stairs",
  "house-robber",
  "house-robber-ii",
  "longest-palindromic-substring",
  "palindromic-substrings",
  "decode-ways",
  "coin-change",
  "maximum-product-subarray",
  "word-break",
  "longest-increasing-subsequence",
  "partition-equal-subset-sum",
  "longest-common-subsequence",
  "best-time-to-buy-and-sell-stock-with-cooldown",
  "target-sum",
  "interleaving-string",
  "longest-increasing-path-in-a-matrix",
  "distinct-subsequences",
  "edit-distance",
  "burst-balloons",
  "regular-expression-matching",
  // Greedy
  "maximum-subarray",
  "jump-game",
  "jump-game-ii",
  "gas-station",
  "hand-of-straights",
  "merge-triplets-to-form-target-triplet",
  "partition-labels",
  "valid-parenthesis-string",
  // Intervals
  "insert-interval",
  "merge-intervals",
  "non-overlapping-intervals",
  // Math & Geometry
  "rotate-image",
  "spiral-matrix",
  "set-matrix-zeroes",
  "happy-number",
  "plus-one",
  "powx-n",
  "multiply-strings",
  // Bit Manipulation
  "single-number",
  "number-of-1-bits",
  "counting-bits",
  "reverse-bits",
  "missing-number",
  "sum-of-two-integers",
  // Advanced Graphs
  "reconstruct-itinerary",
  "min-cost-to-connect-all-points",
  "network-delay-time",
  "swim-in-rising-water",
  "cheapest-flights-within-k-stops",
  // Unique paths
  "unique-paths",
  "find-the-duplicate-number",
]);

export const GRIND_75: ReadonlySet<string> = new Set([
  "two-sum",
  "valid-parentheses",
  "merge-two-sorted-lists",
  "best-time-to-buy-and-sell-stock",
  "valid-palindrome",
  "invert-binary-tree",
  "valid-anagram",
  "binary-search",
  "linked-list-cycle",
  "maximum-depth-of-binary-tree",
  "contains-duplicate",
  "maximum-subarray",
  "climbing-stairs",
  "longest-palindromic-substring",
  "reverse-linked-list",
  "majority-element",
  "add-binary",
  "diameter-of-binary-tree",
  "middle-of-the-linked-list",
  "balanced-binary-tree",
  "first-bad-version",
  "same-tree",
  "subtree-of-another-tree",
  "lowest-common-ancestor-of-a-binary-tree",
  "insert-interval",
  "3sum",
  "binary-tree-level-order-traversal",
  "evaluate-reverse-polish-notation",
  "product-of-array-except-self",
  "course-schedule",
  "validate-binary-search-tree",
  "number-of-islands",
  "rotting-oranges",
  "search-in-rotated-sorted-array",
  "coin-change",
  "longest-substring-without-repeating-characters",
  "longest-repeating-character-replacement",
  "combination-sum",
  "permutations",
  "merge-intervals",
  "sort-colors",
  "container-with-most-water",
  "kth-smallest-element-in-a-bst",
  "minimum-window-substring",
  "word-break",
  "longest-increasing-subsequence",
  "unique-paths",
  "jump-game",
  "binary-tree-right-side-view",
  "construct-binary-tree-from-preorder-and-inorder-traversal",
  "top-k-frequent-elements",
  "task-scheduler",
  "k-closest-points-to-origin",
  "word-search",
  "merge-k-sorted-lists",
  "largest-rectangle-in-histogram",
  "trapping-rain-water",
  "binary-tree-maximum-path-sum",
  "maximum-product-subarray",
  "find-minimum-in-rotated-sorted-array",
  "decode-ways",
  "partition-equal-subset-sum",
  "house-robber",
  "house-robber-ii",
  "longest-common-subsequence",
  "spiral-matrix",
  "subsets",
  "non-overlapping-intervals",
  "pacific-atlantic-water-flow",
  "kth-largest-element-in-an-array",
  "daily-temperatures",
  "sliding-window-maximum",
  "generate-parentheses",
  "set-matrix-zeroes",
  "rotate-image",
]);

export type CuratedListKey = "all" | "neetcode-150" | "blind-75" | "grind-75";

export const CURATED_LISTS: Record<Exclude<CuratedListKey, "all">, ReadonlySet<string>> = {
  "neetcode-150": NEETCODE_150,
  "blind-75": BLIND_75,
  "grind-75": GRIND_75,
};

export const CURATED_LIST_LABELS: Record<CuratedListKey, string> = {
  "all": "All",
  "neetcode-150": "NeetCode 150",
  "blind-75": "Blind 75",
  "grind-75": "Grind 75",
};
