version: "3"
services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: recursev2-piston-1
    restart: always
    privileged: true
    environment:
      - PISTON_OUTPUT_MAX_SIZE=10000000
      - PISTON_MAX_OUTPUT_MAX_SIZE=10000000
      - PISTON_RUN_TIMEOUT=30000
      - PISTON_MAX_RUN_TIMEOUT=30000
      - PISTON_COMPILE_TIMEOUT=30000
      - PISTON_MAX_COMPILE_TIMEOUT=30000
      - PISTON_RUN_MEMORY_LIMIT=536870912
      - PISTON_COMPILE_MEMORY_LIMIT=536870912
    ports:
      - "2000:2000"
    volumes:
      - piston_packages:/piston/packages
    tmpfs:
      - /tmp:exec

volumes:
  piston_packages:
